<template>
    <div class="jy-mulu">
        <v-header :title="title" @back="back" :next="next"></v-header>
        <formList :list="list" ref="choosed" @pop="pop"></formList>
        <pop :options="options" ref="pop" @choosed="choosed"></pop>
    </div>
</template>
<script>
import vHeader from 'base/header/header'
import pop from 'base/pop-up/pop-up'
import formList from 'components/form-list/form-list'
import {mapGetters} from 'vuex'
export default {
  data(){
      return{
          title:'资料目录表',
          next:'提交',
          options:[],
          jyList:[
              {
                  class:'collapse-wrapper',
                  name:'借款人身份证',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'借款人户口',
                  checked:false,
                  options:['原件','复印件','首页','户主页','本人页'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'借款人配偶身份证',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'借款人配偶户口',
                  checked:false,
                  options:['原件','复印件','首页','户主页','本人页'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'婚姻证明',
                  checked:false,
                  options:['原件','复印件','结婚证','离婚证','离婚协议'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'抵押物房产两证',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'资产证明复印件',
                  checked:false,
                  options:['原件','复印件','房产证','车产证','其他资产'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'收入证明',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'营业执照（三证合一）',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'企业法定代表人身份证',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'公司章程',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'经营地租赁合同或产权证明',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'贸易合同',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'用途合同',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'其他',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              }
          ],
          xfList:[
              {
                  class:'collapse-wrapper',
                  name:'借款人身份证',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'借款人户口',
                  checked:false,
                  options:['原件','复印件','首页','户主页','本人页'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'借款人配偶身份证',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'借款人配偶户口',
                  checked:false,
                  options:['原件','复印件','首页','户主页','本人页'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'婚姻证明',
                  checked:false,
                  options:['原件','复印件','结婚证','离婚证','离婚协议'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'抵押物房产两证',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'资产证明复印件',
                  checked:false,
                  options:['原件','复印件','房产证','车产证','其他资产'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'收入证明',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'用途合同',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              },{
                  class:'collapse-wrapper',
                  name:'其他',
                  checked:false,
                  options:['原件','复印件'],
                  checkList:[],
                  page:'',
              }
          ],
          list:[{
              title:'',
              items:[
                  {
                      class:"select-wrapper",
                      text:'完成日期',
                      value:'',
                      options:[]
                  },{
                      class:"normal-wrapper",
                      text:'资料收集情况',
                      value:'已完成',
                  }
              ]
          },{
              title:'资料明细',
              items:[]
          }]
      }
  },
  computed:{
      ...mapGetters([
          'customer'
      ])
  },
  methods:{
      back(){
          this.$router.back()
      },
      init(){
          if(this.customer.id %2 === 1){
              this.list[1].items = this.jyList
          }else{
              this.list[1].items = this.xfList
          }
      },
      pop(option){
          this.options = option
          this.$refs.pop.show()
      },
      choosed(option){
          this.$refs.formList.choosed(option)
      }
  },
  mounted(){
      this.init()
  },
  components:{
      vHeader,
      formList,
      pop
  }
}
</script>
<style lang="stylus" scoped>
@import "~common/stylus/variable"
.jy-mulu
    position absolute 
    top 0
    bottom 0
    left 0
    right 0
    background $color-background
    
</style>
